# Generated by Django 4.0.4 on 2022-05-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='private_key',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='eth_address',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
