# Generated by Django 4.0.4 on 2022-05-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_private_key_alter_customuser_eth_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='eth_address',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='private_key',
            field=models.CharField(default=0, max_length=60),
        ),
    ]
