# Generated by Django 4.0.4 on 2022-05-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_eth_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='private_key',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
