# Generated by Django 4.0.4 on 2022-05-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web3app', '0003_alter_proposal_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='options',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='voters',
            field=models.IntegerField(default=0),
        ),
    ]
