# Generated by Django 4.0.4 on 2022-05-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web3app', '0004_proposal_options_proposal_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='end_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='options',
            field=models.CharField(max_length=500),
        ),
    ]
