# Generated by Django 4.0.4 on 2022-06-10 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web3app', '0006_alter_proposal_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web3Deploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proposal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web3app.proposal')),
            ],
        ),
    ]
