# Generated by Django 4.0.4 on 2022-06-13 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web3app', '0009_web3deploy_contract_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingVoters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_voting', models.DateTimeField(default=django.utils.timezone.now)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web3app.proposal')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
