# Generated by Django 4.0.4 on 2022-06-13 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web3app', '0011_alter_proposal_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
