# Generated by Django 4.0.4 on 2022-06-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web3app', '0012_alter_proposal_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
