# Generated by Django 4.0.4 on 2022-06-13 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web3app', '0014_alter_proposal_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
