# Generated by Django 4.0.4 on 2022-06-13 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web3app', '0015_alter_proposal_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 21, 17, 33, 526002)),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 21, 17, 33, 526002)),
        ),
    ]
